export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
export const brands = [
  "Kellogg's",
  "Heinz",
  "Nestlé",
  "Coca-Cola",
  "Quaker Oats",
  "Campbell's",
  "Kraft",
  "Pepsi",
  "General Mills",
  "Procter & Gamble",
  "Johnson & Johnson",
  "Unilever",
  "Mars",
  "Hershey's",
  "Nabisco",
  "Frito-Lay",
  "ConAgra Brands",
  "Tyson Foods",
  "Ocean Spray",
  "Dole",
  "Del Monte",
  "Smucker's",
  "McCormick",
  "Breyers",
  "Green Giant",
  "Gatorade",
  "Welch's",
  "Tropicana",
  "Huggies",
  "Colgate-Palmolive",
];
